# Generated by Django 6.1 on 2026-08-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='магазин')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='название магазина')),
                ('days', models.PositiveSmallIntegerField(default=30, verbose_name='период анализа, дней')),
                ('horizon', models.PositiveSmallIntegerField(default=14, verbose_name='закупаем на, дней')),
                ('status', models.CharField(choices=[('building', 'Считается'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='building', max_length=16, verbose_name='статус')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('items_total', models.PositiveIntegerField(default=0, verbose_name='позиций требует заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='сумма закупа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('built_at', models.DateTimeField(blank=True, null=True, verbose_name='посчитан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_plans', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'план закупа',
                'verbose_name_plural': 'планы закупа',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchasePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='№')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('sold', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='продано за период')),
                ('stock', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='остаток')),
                ('per_day', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='расход в день')),
                ('cover_days', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='хватит на, дней')),
                ('suggested', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='заказать')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='закупочная')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='на сумму')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseplan', verbose_name='план')),
            ],
            options={
                'verbose_name': 'строка плана закупа',
                'verbose_name_plural': 'строки плана закупа',
                'ordering': ('position',),
            },
        ),
    ]
