# Generated by Django 6.1 on 2026-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplanitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='поставщик'),
        ),
    ]
