# Generated by Django 6.1 on 2026-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseplanitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='use_stock',
            field=models.BooleanField(default=True, verbose_name='учитывать остаток'),
        ),
    ]
