# Generated by Django 6.1 on 2026-09-07 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseplan_use_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='магазин')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='название магазина')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='поставщик')),
                ('items_total', models.PositiveIntegerField(default=0, verbose_name='позиций')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='сумма')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='одобрен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_purchases', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'одобренный закуп',
                'verbose_name_plural': 'одобренные закупки',
                'ordering': ('-approved_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovedPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='№')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('sold', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='продано за период')),
                ('stock', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='остаток')),
                ('per_day', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='расход в день')),
                ('cover_days', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='хватит на, дней')),
                ('suggested', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='заказать')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='закупочная')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='на сумму')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.approvedpurchase', verbose_name='закуп')),
            ],
            options={
                'verbose_name': 'строка одобренного закупа',
                'verbose_name_plural': 'строки одобренного закупа',
                'ordering': ('position',),
            },
        ),
    ]
