# Generated by Django 6.1 on 2026-09-08

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_approved_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplanitem',
            name='forecast_model',
            field=models.CharField(default='average', max_length=32, verbose_name='модель прогноза'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='forecast_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='прогноз на горизонт'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='forecast_per_day',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='прогноз в день'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='safety_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='страховой запас'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='holiday_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, verbose_name='коэффициент праздников'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='forecast_error',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='ошибка прогноза'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='forecast_model',
            field=models.CharField(default='average', max_length=32, verbose_name='модель прогноза'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='forecast_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='прогноз на горизонт'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='forecast_per_day',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='прогноз в день'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='safety_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='страховой запас'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='holiday_factor',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, verbose_name='коэффициент праздников'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='forecast_error',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='ошибка прогноза'),
        ),
    ]
