# Generated by Django 6.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_forecast_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название'),
        ),
    ]
