# Generated by Django 6.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplanitem',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='скоропортящийся'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='shelf_life_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='срок годности, дней'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='purchase_horizon',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='эффективный горизонт закупа'),
        ),
        migrations.AddField(
            model_name='purchaseplanitem',
            name='perishability_source',
            field=models.CharField(blank=True, max_length=16, verbose_name='источник срока годности'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='скоропортящийся'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='shelf_life_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='срок годности, дней'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='purchase_horizon',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='эффективный горизонт закупа'),
        ),
        migrations.AddField(
            model_name='approvedpurchaseitem',
            name='perishability_source',
            field=models.CharField(blank=True, max_length=16, verbose_name='источник срока годности'),
        ),
    ]
