services:
  db:
    image: postgres:17-alpine
    container_name: tvoy_magazin_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tvoy_magazin
      POSTGRES_USER: tvoy_magazin
      POSTGRES_PASSWORD: tvoy_magazin
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tvoy_magazin -d tvoy_magazin']
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  db:
