# Generated by Django 6.1 on 2026-08-11 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='invoices/%Y/%m', verbose_name='фото накладной')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('error', models.TextField(blank=True, verbose_name='ошибка разбора')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='поставщик')),
                ('supplier_bin', models.CharField(blank=True, max_length=32, verbose_name='БИН поставщика')),
                ('number', models.CharField(blank=True, max_length=64, verbose_name='номер документа')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='дата документа')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='итого по накладной')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='модель распознавания')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='ответ модели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='разобрано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'накладная',
                'verbose_name_plural': 'накладные',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='№ строки')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='штрихкод')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='количество')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='единица измерения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена по накладной')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'позиция накладной',
                'verbose_name_plural': 'позиции накладной',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('invoice', 'position'), name='unique_line_position')],
            },
        ),
    ]
