# Generated by Django 6.1 on 2026-08-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='проверено'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_invoices', to=settings.AUTH_USER_MODEL, verbose_name='проверил'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готово'), ('checked', 'Проверено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус'),
        ),
    ]
