# Generated by Django 6.1 on 2026-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_checked_at_invoice_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='потрачено на разбор, $'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='preview',
            field=models.FileField(blank=True, upload_to='invoices/%Y/%m/preview', verbose_name='превью'),
        ),
    ]
