# Generated by Django 6.1 on 2026-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_cost_invoice_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='umag_pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='отправлено в UMAG'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='umag_supply_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='приёмка в UMAG'),
        ),
    ]
