# Generated by Django 6.1 on 2026-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_umag_pushed_at_invoice_umag_supply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='umag_store_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='магазин в UMAG'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='umag_store_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название магазина'),
        ),
    ]
