# Generated by Django 6.1 on 2026-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_umag_store_id_invoice_umag_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='umag_barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='штрихкод в UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='уверенность сопоставления'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_product_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='товар в UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название в UMAG'),
        ),
    ]
