# Generated by Django 6.1 on 2026-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceline_umag_barcode_invoiceline_umag_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_bin_auto',
            field=models.BooleanField(default=False, verbose_name='БИН подставлен'),
        ),
    ]
