# Generated by Django 6.1 on 2026-08-19 16:55

from django.db import migrations, models


def mark_checked_invoices(apps, schema_editor):
    """Проверенные до появления флага годятся в обучение ровно так же.

    Признак тут не дата загрузки, а то, что человек сверил строки с бумагой, —
    иначе флаг стоял бы у одних выверенных накладных и не стоял у других.
    """

    Invoice = apps.get_model('invoices', 'Invoice')
    Invoice.objects.filter(checked_at__isnull=False).update(for_training=True)


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_supplier_bin_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='for_training',
            field=models.BooleanField(default=False, verbose_name='годится для обучения'),
        ),
        # Флаг снимается руками, если снимок окажется негодным, — назад
        # раскатывать нечего.
        migrations.RunPython(mark_checked_invoices, migrations.RunPython.noop),
    ]
