# Generated by Django 6.1 on 2026-08-20 04:38

import django.db.models.deletion
from django.db import migrations, models


def move_invoices_into_organizations(apps, schema_editor):
    """Раскладывает уже загруженные накладные по организациям тех, кто их завёл.

    Организации людям раздала миграция accounts.0002, так что здесь остаётся
    взять её у автора накладной. Пользователя без организации быть не должно,
    но если он найдётся — накладную не теряем, а заводим ей организацию сами:
    удалить её потом дешевле, чем искать пропавшие документы.
    """

    Invoice = apps.get_model('invoices', 'Invoice')
    Organization = apps.get_model('accounts', 'Organization')

    spare = None

    for invoice in Invoice.objects.filter(organization__isnull=True).select_related('created_by'):
        organization_id = invoice.created_by.organization_id

        if organization_id is None:
            spare = spare or Organization.objects.create(name='Без организации')
            organization_id = spare.pk

        invoice.organization_id = organization_id
        invoice.save(update_fields=('organization',))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizations'),
        ('invoices', '0009_invoice_for_training_alter_invoice_preview'),
    ]

    operations = [
        # Поле появляется необязательным: у существующих строк его ещё нечем
        # заполнить. Заполняем — и только потом требуем.
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='accounts.organization',
                verbose_name='организация',
            ),
        ),
        migrations.RunPython(move_invoices_into_organizations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='invoices',
                to='accounts.organization',
                verbose_name='организация',
            ),
        ),
    ]
