# Generated by Django 6.1 on 2026-08-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='invoices/%Y/%m', verbose_name='лист накладной')),
                ('position', models.PositiveSmallIntegerField(default=2, verbose_name='№ листа')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='invoices.invoice', verbose_name='накладная')),
            ],
            options={
                'verbose_name': 'лист накладной',
                'verbose_name_plural': 'листы накладной',
                'ordering': ('position',),
            },
        ),
    ]
