# Generated by Django 6.1 on 2026-08-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='invoices/%Y/%m/thumb', verbose_name='миниатюра'),
        ),
    ]
