# Generated by Django 6.1 on 2026-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='barcode_auto',
            field=models.BooleanField(default=False, verbose_name='штрихкод подобран'),
        ),
    ]
