# Generated by Django 6.1 on 2026-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoiceline_barcode_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='umag_missing',
            field=models.BooleanField(default=False, verbose_name='нет в UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_new_category_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='категория в UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_new_measure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 — штучный, 1 — весовой, 2 — разливной', null=True, verbose_name='единица в UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_new_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название для UMAG'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='umag_new_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена продажи'),
        ),
    ]
