# Generated by Django 6.1 on 2026-08-20 04:38

import django.db.models.deletion
from django.db import migrations, models


def give_everyone_an_organization(apps, schema_editor):
    """Заводит организацию каждому, кто работал до их появления.

    Каждому свою, а не одну на всех: до этой миграции данные были разложены по
    людям, и свалив их в общую организацию мы бы показали чужие накладные всем.
    Объединить две организации потом — работа на минуту, разделить обратно —
    уже не всегда возможно.

    Роль тут не трогаем: её раздаёт человек, а не миграция. Все останутся
    менеджерами, пока владельца не назначат руками в админке.

    Суперпользователя пропускаем: он ходит в админку Django, а не в кабинет.
    """

    User = apps.get_model('accounts', 'User')
    Organization = apps.get_model('accounts', 'Organization')

    for user in User.objects.filter(organization__isnull=True, is_superuser=False):
        organization = Organization.objects.create(name=user.name or user.email)
        user.organization = organization
        user.save(update_fields=('organization',))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер')], default='manager', max_length=16, verbose_name='роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.organization', verbose_name='организация'),
        ),
        # Организации назад не разбираем: удалять их вслепую опаснее, чем
        # оставить лишние.
        migrations.RunPython(give_everyone_an_organization, migrations.RunPython.noop),
    ]
