# Generated by Django 6.1 on 2026-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assistant_access',
            field=models.BooleanField(default=False, verbose_name='доступ к помощнику'),
        ),
        migrations.AddField(
            model_name='user',
            name='purchases_access',
            field=models.BooleanField(default=False, verbose_name='доступ к закупкам'),
        ),
    ]
