# Generated by Django 6.1 on 2026-08-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='По нему фронт находит свою реализацию: umag', unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('summary', models.CharField(help_text='Строка под названием', max_length=255, verbose_name='коротко')),
                ('description', models.TextField(help_text='Абзацы разделяются пустой строкой', verbose_name='описание')),
                ('logo', models.CharField(blank=True, help_text='Путь во фронте (/logos/umag.svg) или полный адрес картинки', max_length=255, verbose_name='логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать в каталоге')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'расширение',
                'verbose_name_plural': 'расширения',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExtensionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='что даёт')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='extensions.extension', verbose_name='расширение')),
            ],
            options={
                'verbose_name': 'возможность расширения',
                'verbose_name_plural': 'возможности расширения',
                'ordering': ('position', 'id'),
            },
        ),
    ]
