# Generated by Django 6.1 on 2026-08-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='подключено')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='extensions.extension', verbose_name='расширение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_installs', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подключённое расширение',
                'verbose_name_plural': 'подключённые расширения',
                'constraints': [models.UniqueConstraint(fields=('user', 'extension'), name='unique_extension_install')],
            },
        ),
    ]
