# Generated by Django 6.1 on 2026-08-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_extensioninstall'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='extensions.extension', verbose_name='обязательные расширения'),
        ),
    ]
