# Generated by Django 6.1 on 2026-08-13 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('name', models.CharField(max_length=255, verbose_name='поставщик из накладной')),
                ('agent_id', models.PositiveIntegerField(verbose_name='контрагент в UMAG')),
                ('agent_name', models.CharField(blank=True, max_length=255, verbose_name='название контрагента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'связка поставщика',
                'verbose_name_plural': 'связки поставщиков',
                'constraints': [models.UniqueConstraint(fields=('store_id', 'name'), name='unique_supplier_link')],
            },
        ),
        migrations.CreateModel(
            name='UmagAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, verbose_name='логин в UMAG')),
                ('token', models.CharField(max_length=255, verbose_name='токен сессии')),
                ('store_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='магазин')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='название магазина')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='подключено')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='токен обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umag_account', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'доступ в UMAG',
                'verbose_name_plural': 'доступы в UMAG',
            },
        ),
    ]
