# Generated by Django 6.1 on 2026-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umag', '0002_umagaccount_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmagProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('barcode', models.CharField(max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('search_name', models.CharField(blank=True, max_length=255, verbose_name='название для поиска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'товар в UMAG',
                'verbose_name_plural': 'номенклатура UMAG',
                'indexes': [models.Index(fields=['store_id'], name='umag_umagpr_store_i_f0bb0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id', 'barcode'), name='unique_store_product')],
            },
        ),
    ]
