# Generated by Django 6.1 on 2026-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umag', '0003_umagproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='umagaccount',
            name='stores',
            field=models.JSONField(blank=True, default=list, verbose_name='магазины'),
        ),
    ]
