# Generated by Django 6.1 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_section_access'),
        ('umag', '0004_account_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmagSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('external_id', models.CharField(max_length=64, verbose_name='ID в UMAG')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='продажа')),
                ('receipt_no', models.CharField(blank=True, max_length=64, verbose_name='номер чека')),
                ('pos_id', models.CharField(blank=True, max_length=64, verbose_name='касса')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('is_ofd', models.BooleanField(blank=True, null=True, verbose_name='фискализирован')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umag_sales', to='accounts.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'продажа UMAG',
                'verbose_name_plural': 'продажи UMAG',
            },
        ),
        migrations.CreateModel(
            name='UmagSalesSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('status', models.CharField(choices=[('syncing', 'Загружается'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='syncing', max_length=16, verbose_name='статус')),
                ('history_from', models.DateTimeField(blank=True, null=True, verbose_name='история начинается')),
                ('synced_until', models.DateTimeField(blank=True, null=True, verbose_name='синхронизировано по')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='синхронизировано')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umag_sales_syncs', to='accounts.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'синхронизация продаж UMAG',
                'verbose_name_plural': 'синхронизации продаж UMAG',
            },
        ),
        migrations.CreateModel(
            name='UmagSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='№')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='цена')),
                ('price_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='цена до скидки')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='сумма')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='umag.umagsale', verbose_name='продажа')),
            ],
            options={
                'verbose_name': 'строка продажи UMAG',
                'verbose_name_plural': 'строки продаж UMAG',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='UmagRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('external_id', models.CharField(max_length=64, verbose_name='ID в UMAG')),
                ('sale_external_id', models.CharField(blank=True, max_length=64, verbose_name='ID продажи в UMAG')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='возврат')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='выплачено')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umag_refunds', to='accounts.organization', verbose_name='организация')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='umag.umagsale', verbose_name='продажа')),
            ],
            options={
                'verbose_name': 'возврат UMAG',
                'verbose_name_plural': 'возвраты UMAG',
            },
        ),
        migrations.CreateModel(
            name='UmagRefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='№')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='цена')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='сумма')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='umag.umagrefund', verbose_name='возврат')),
            ],
            options={
                'verbose_name': 'строка возврата UMAG',
                'verbose_name_plural': 'строки возврата UMAG',
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='umagsale',
            constraint=models.UniqueConstraint(fields=('organization', 'store_id', 'external_id'), name='unique_organization_store_sale'),
        ),
        migrations.AddIndex(
            model_name='umagsale',
            index=models.Index(fields=['organization', 'store_id', 'occurred_at'], name='umag_umagsa_organiz_dfe0e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='umagsalessync',
            constraint=models.UniqueConstraint(fields=('organization', 'store_id'), name='unique_organization_store_sales_sync'),
        ),
        migrations.AddConstraint(
            model_name='umagsaleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'position'), name='unique_sale_position'),
        ),
        migrations.AddConstraint(
            model_name='umagrefund',
            constraint=models.UniqueConstraint(fields=('organization', 'store_id', 'external_id'), name='unique_organization_store_refund'),
        ),
        migrations.AddIndex(
            model_name='umagrefund',
            index=models.Index(fields=['organization', 'store_id', 'occurred_at'], name='umag_umagre_organiz_f838b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='umagrefunditem',
            constraint=models.UniqueConstraint(fields=('refund', 'position'), name='unique_refund_position'),
        ),
    ]
