# Generated by Django 6.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umag', '0005_sales_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='umagproduct',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='umagproduct',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, verbose_name='подкатегория'),
        ),
        migrations.AddField(
            model_name='umagproduct',
            name='shelf_life_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — определить автоматически; 0 — не ограничивать закуп', null=True, verbose_name='срок годности, дней'),
        ),
    ]
