# Generated by Django 6.1 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umag', '0006_product_perishability'),
    ]

    operations = [
        migrations.AddField(
            model_name='umagsalessync',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя активность'),
        ),
    ]
