# Generated by Django 6.1 on 2026-09-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_section_access'),
        ('umag', '0007_sales_sync_heartbeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umagrefund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='umagrefund',
            name='note',
        ),
        migrations.RemoveField(
            model_name='umagrefund',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='umagrefunditem',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='umagrefunditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='umagrefunditem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='umagrefunditem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='umagsale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='umagsale',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='umagsale',
            name='is_ofd',
        ),
        migrations.RemoveField(
            model_name='umagsale',
            name='pos_id',
        ),
        migrations.RemoveField(
            model_name='umagsale',
            name='receipt_no',
        ),
        migrations.RemoveField(
            model_name='umagsaleitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='umagsaleitem',
            name='price_before',
        ),
        migrations.RemoveField(
            model_name='umagsaleitem',
            name='total',
        ),
        migrations.AddField(
            model_name='umagrefund',
            name='folded',
            field=models.BooleanField(default=False, verbose_name='учтён в спросе'),
        ),
        migrations.AddField(
            model_name='umagrefund',
            name='sale_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='продажа'),
        ),
        migrations.CreateModel(
            name='UmagDailyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('barcode', models.CharField(max_length=64, verbose_name='штрихкод')),
                ('day', models.DateField(verbose_name='день')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='количество')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umag_daily_demands', to='accounts.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'дневной спрос UMAG',
                'verbose_name_plural': 'дневной спрос UMAG',
                'indexes': [models.Index(fields=['organization', 'store_id', 'day'], name='umag_umagda_organiz_1fc132_idx'), models.Index(fields=['organization', 'store_id', 'barcode'], name='umag_umagda_organiz_d94c3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'store_id', 'barcode', 'day'), name='unique_organization_store_barcode_day')],
            },
        ),
        migrations.CreateModel(
            name='UmagSoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField(verbose_name='магазин')),
                ('barcode', models.CharField(max_length=64, verbose_name='штрихкод')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='товар')),
                ('measure', models.CharField(blank=True, max_length=32, verbose_name='единица')),
                ('sold', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='продано')),
                ('last_sold', models.DateTimeField(blank=True, null=True, verbose_name='последняя продажа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umag_sold_products', to='accounts.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'проданный товар UMAG',
                'verbose_name_plural': 'проданные товары UMAG',
                'indexes': [models.Index(fields=['organization', 'store_id'], name='umag_umagso_organiz_0a35ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'store_id', 'barcode'), name='unique_organization_store_sold_product')],
            },
        ),
    ]
