# Generated by Django 6.1 on 2026-09-11 06:25

from django.db import migrations, models


def fold_existing_sales(apps, schema_editor):
    """Сворачивает уже лежащие чеки: история в агрегате, сырые — только неделя.

    Делаем это здесь, а не в 0008: свёртка читает текущие модели, и колонка
    `on_promo` к этому моменту уже должна быть в таблице.
    """

    from django.utils import timezone

    from accounts.models import Organization
    from umag.demand import history_start, rebuild_store, trim
    from umag.models import UmagRefund, UmagSale, UmagSalesSync
    from umag.sales import OVERLAP

    for refund in (
        UmagRefund.objects.filter(sale_occurred_at=None)
        .exclude(sale=None)
        .select_related('sale')
        .iterator()
    ):
        UmagRefund.objects.filter(pk=refund.pk).update(sale_occurred_at=refund.sale.occurred_at)

    keep_after = timezone.now() - OVERLAP

    for organization_id, store_id in UmagSale.objects.values_list(
        'organization_id',
        'store_id',
    ).distinct():
        organization = Organization.objects.get(pk=organization_id)
        rebuild_store(organization, store_id)
        trim(organization, store_id, keep_after)
        start = history_start(organization, store_id)
        if start is not None:
            UmagSalesSync.objects.filter(
                organization=organization,
                store_id=store_id,
            ).update(history_from=start)


class Migration(migrations.Migration):

    dependencies = [
        ('umag', '0008_compact_sales_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='umagdailydemand',
            name='promo_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='со скидкой'),
        ),
        migrations.AddField(
            model_name='umagsaleitem',
            name='on_promo',
            field=models.BooleanField(default=False, verbose_name='со скидкой'),
        ),
        migrations.RunPython(fold_existing_sales, migrations.RunPython.noop),
    ]
