"""
Django settings for tvoy_magazin_api project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from . import database

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env(path: Path) -> None:
    """Читает .env вида KEY=value.

    Свой разбор вместо python-dotenv: файл простой, а лишний пакет не нужен.
    Переменные из окружения важнее файла, поэтому setdefault.
    """

    if not path.is_file():
        return

    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()

        if not line or line.startswith('#') or '=' not in line:
            continue

        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# .env лежит рядом с pyproject.toml, на уровень выше manage.py.
load_env(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure--p@@fpie5ee%yq_e-k-(zz19&b#h#*w$@9kuy_1o5b7$m7y0zx',
)

# Отладка выключена по умолчанию: включённой она отдаёт трейсбек со всеми
# настройками — ключом OpenRouter и паролем базы в том числе. Для разработки
# ставится в .env строкой DJANGO_DEBUG=1.
DEBUG = os.environ.get('DJANGO_DEBUG') == '1'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# За обратным прокси Django видит запрос как http и на этом основании
# отвергает вход в админку. Хостинг говорит настоящую схему этим заголовком.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Домены, с которых принимаются формы админки. Без них вход по https
# заканчивается «CSRF verification failed».
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # Отозванные refresh-токены. Приложение идёт внутри simplejwt — отдельного
    # пакета не нужно, только две таблицы под уже недействительные токены.
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'extensions',
    'invoices',
    'purchases',
    'umag',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tvoy_magazin_api.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tvoy_magazin_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tvoy_magazin_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# На хостинге база приходит адресом в `DATABASE_URL` — там это Postgres в
# отдельном контейнере. Локально переменной нет, и работает файловый SQLite:
# ставить Postgres на машину ради разработки незачем.
DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    DATABASES = {'default': database.from_url(DATABASE_URL)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # Отдельный файл базы пригождается для проверок на живом API.
            'NAME': os.environ.get('DJANGO_DB_NAME') or BASE_DIR / 'db.sqlite3',
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Сюда `collectstatic` складывает оформление админки. С выключенной отладкой
# Django перестаёт искать файлы по приложениям, и без этой папки админка
# открывается голым текстом.
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT') or BASE_DIR / 'staticfiles')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'UNAUTHENTICATED_USER': None,
}

# Токенов два. Access живёт час и ходит в каждом запросе; refresh лежит у
# фронта и меняется на новый access, когда прежний протух. Раньше access был
# один и жил 12 часов — украденный работал все двенадцать, и отобрать его было
# нечем. Короткий access сам закрывает окно, а refresh отзывается по списку.
#
# ACCESS_TOKEN_HOURS остался прежним именем ради уже настроенных окружений.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        hours=int(os.environ.get('ACCESS_TOKEN_HOURS', '1')),
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.environ.get('REFRESH_TOKEN_DAYS', '30')),
    ),
    # Обновление выдаёт новый refresh, а прежний уходит в чёрный список: если
    # его успели украсть, вторым обновлением воспользоваться уже нельзя.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

MEDIA_URL = 'media/'
# Фотографии накладных переживают деплой только на примонтированном томе:
# файловая система контейнера эфемерна. Локально — обычная папка рядом с кодом.
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or BASE_DIR / 'media')

# Загруженное фото накладной целиком уходит в память при разборе,
# так что держим лимит близко к проверке в сериализаторе.
DATA_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024

# Свой CORS вместо django-cors-headers: фронт на Angular стоит отдельно.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:4200,http://127.0.0.1:4200',
).split(',')

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_VISION_MODEL = os.environ.get(
    'OPENROUTER_VISION_MODEL',
    'openai/gpt-5.6-luna',
)
OPENROUTER_TIMEOUT = int(os.environ.get('OPENROUTER_TIMEOUT', '120'))

# Сопоставление позиций с номенклатурой UMAG и поставщиков между собой.
# Задача текстовая: выбрать нужное из десятка кандидатов, которые подобрал наш
# код. Зрение и рассуждения тут ни к чему, поэтому модель дешевле той, что
# читает фотографии. Не задана — берём ту же, что и для распознавания.
OPENROUTER_MATCH_MODEL = os.environ.get(
    'OPENROUTER_MATCH_MODEL',
    'deepseek/deepseek-v4-flash',
)

# Запасные модели на случай, когда основная занята: OpenRouter пройдёт по списку.
OPENROUTER_FALLBACK_MODELS = [
    model.strip()
    for model in os.environ.get('OPENROUTER_FALLBACK_MODELS', '').split(',')
    if model.strip()
]

# Кабинет UMAG: публичного API нет, всё снято с их фронта (см. umag-api.md).
# Версии клиента лежат в заголовках: без них сервер считает нас устаревшими.
UMAG_BASE_URL = os.environ.get('UMAG_BASE_URL', 'https://api.umag.kz/rest/cabinet/')
UMAG_API_VERSION = os.environ.get('UMAG_API_VERSION', '1.4')
UMAG_CLIENT_VERSION = os.environ.get('UMAG_CLIENT_VERSION', 'angular_cabinet_20.0.24')
UMAG_TIMEOUT = int(os.environ.get('UMAG_TIMEOUT', '30'))

# Ссылка на созданный черновик — её показываем человеку после отправки.
UMAG_SUPPLY_URL = os.environ.get(
    'UMAG_SUPPLY_URL',
    'https://web.umag.kz/store/0/supplies/{id}/edit',
)

# Сколько накладных разбираем одновременно.
INVOICE_PARSE_CONCURRENCY = int(os.environ.get('INVOICE_PARSE_CONCURRENCY', '1'))

# Разбирать накладную прямо в запросе, без фонового потока: удобно в тестах
# и когда нужно увидеть ошибку модели сразу.
INVOICE_PARSE_INLINE = os.environ.get('INVOICE_PARSE_INLINE') == '1'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
