"""
Django settings for tvoy_magazin_api project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env(path: Path) -> None:
    """Читает .env вида KEY=value.

    Свой разбор вместо python-dotenv: файл простой, а лишний пакет не нужен.
    Переменные из окружения важнее файла, поэтому setdefault.
    """

    if not path.is_file():
        return

    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()

        if not line or line.startswith('#') or '=' not in line:
            continue

        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# .env лежит рядом с pyproject.toml, на уровень выше manage.py.
load_env(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure--p@@fpie5ee%yq_e-k-(zz19&b#h#*w$@9kuy_1o5b7$m7y0zx',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'extensions',
    'invoices',
    'purchases',
    'umag',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tvoy_magazin_api.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tvoy_magazin_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tvoy_magazin_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Отдельный файл базы пригождается для проверок на живом API.
        'NAME': os.environ.get('DJANGO_DB_NAME') or BASE_DIR / 'db.sqlite3',
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'UNAUTHENTICATED_USER': None,
}

# Токен один — access. Refresh не выдаём и не принимаем, поэтому живёт он долго.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        hours=int(os.environ.get('ACCESS_TOKEN_HOURS', '12')),
    ),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Загруженное фото накладной целиком уходит в память при разборе,
# так что держим лимит близко к проверке в сериализаторе.
DATA_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024

# Свой CORS вместо django-cors-headers: фронт на Angular стоит отдельно.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:4200,http://127.0.0.1:4200',
).split(',')

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_VISION_MODEL = os.environ.get(
    'OPENROUTER_VISION_MODEL',
    'qwen/qwen3.7-plus',
)
OPENROUTER_TIMEOUT = int(os.environ.get('OPENROUTER_TIMEOUT', '120'))

# Сопоставление позиций с номенклатурой UMAG — задача текстовая, но модель
# та же: отдельную заводить незачем, пока эта справляется.
OPENROUTER_MATCH_MODEL = os.environ.get('OPENROUTER_MATCH_MODEL', OPENROUTER_VISION_MODEL)

# Запасные модели на случай, когда основная занята: OpenRouter пройдёт по списку.
OPENROUTER_FALLBACK_MODELS = [
    model.strip()
    for model in os.environ.get('OPENROUTER_FALLBACK_MODELS', '').split(',')
    if model.strip()
]

# Кабинет UMAG: публичного API нет, всё снято с их фронта (см. umag-api.md).
# Версии клиента лежат в заголовках: без них сервер считает нас устаревшими.
UMAG_BASE_URL = os.environ.get('UMAG_BASE_URL', 'https://api.umag.kz/rest/cabinet/')
UMAG_API_VERSION = os.environ.get('UMAG_API_VERSION', '1.4')
UMAG_CLIENT_VERSION = os.environ.get('UMAG_CLIENT_VERSION', 'angular_cabinet_20.0.24')
UMAG_TIMEOUT = int(os.environ.get('UMAG_TIMEOUT', '30'))

# Ссылка на созданный черновик — её показываем человеку после отправки.
UMAG_SUPPLY_URL = os.environ.get(
    'UMAG_SUPPLY_URL',
    'https://web.umag.kz/store/0/supplies/{id}/edit',
)

# Сколько накладных разбираем одновременно.
INVOICE_PARSE_CONCURRENCY = int(os.environ.get('INVOICE_PARSE_CONCURRENCY', '1'))

# Разбирать накладную прямо в запросе, без фонового потока: удобно в тестах
# и когда нужно увидеть ошибку модели сразу.
INVOICE_PARSE_INLINE = os.environ.get('INVOICE_PARSE_INLINE') == '1'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
