# Generated by Django 6.1 on 2026-08-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='начата')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chat', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'переписка с аналитиком',
                'verbose_name_plural': 'переписки с аналитиком',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Человек'), ('assistant', 'Аналитик')], max_length=16, verbose_name='кто')),
                ('text', models.TextField(verbose_name='текст')),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='потрачено, $')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='переписка')),
            ],
            options={
                'verbose_name': 'реплика',
                'verbose_name_plural': 'реплики',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
