# Generated by Django 6.1 on 2026-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, upload_to='assistant/%Y/%m', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
