# Generated by Django 6.1 on 2026-08-25 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from assistant.models import TITLE


def name_old_chats(apps, schema_editor):
    """Называет уже заведённые переписки их первым вопросом.

    Без этого весь прежний разговор — а он у человека один и как раз самый
    нужный — оказался бы в истории строкой «Без названия».
    """

    Conversation = apps.get_model('assistant', 'Conversation')

    for chat in Conversation.objects.all():
        first = chat.messages.filter(role='user').order_by('created_at', 'id').first()
        text = ' '.join((first.text if first else '').split()) or 'Фото'
        chat.title = text if len(text) <= TITLE else f'{text[: TITLE - 1].rstrip()}…'
        chat.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_message_image_alter_message_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-updated_at', '-id'), 'verbose_name': 'переписка с аналитиком', 'verbose_name_plural': 'переписки с аналитиком'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=80, verbose_name='о чём'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='последняя реплика'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chats', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        # Назад откатывать нечего: без поля `title` названию негде храниться.
        migrations.RunPython(name_old_chats, migrations.RunPython.noop),
    ]
