# Generated by Django 6.1 on 2026-09-19 15:30

import assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_conversation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to=assistant.models.report_path, verbose_name='файл'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='имя файла'),
        ),
    ]
